# Generated by Django 4.2 on 2023-06-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestName', models.CharField(max_length=255)),
                ('requestUser', models.CharField(max_length=255)),
                ('requestDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestCode', models.IntegerField()),
                ('captureRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soar.capturerequest')),
            ],
        ),
    ]
